basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('accounts.urls', namespace='account'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'
urlpatterns = [
    path('home/', views.home, name='home'),
    path('item/<slug:slug>/', views.product_details, name='product_details'),
    path('category/<slug:slug>/', views.category_list, name='category_details'),
]

basket/models.py
from django.db import models

# Create your models here.

store/models.py
from django.db import models
from django.urls import reverse

from core import settings


class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('store:category_details', args=[self.slug, ])

    class Meta:
        verbose_name_plural = 'Categories'


class Product(models.Model):
    category = models.ForeignKey(
        Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(
        upload_to='products_images/', default='default-gray.png')
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=4, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductManager()

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('store:product_details', args=[self.slug, ])

basket/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render

from store.models import Product

from .basket import Basket

# from django.contrib.sessions.models import Session


def basket_summary(request):
    basket = Basket(request)
    return render(request, 'store/basket/summary.html', {'basket': basket})


def basket_add(request):
    basket = Basket(request)
    if request.method == 'POST':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        print(product_id, '🌹🌹🌹🌹🌹')
        product = get_object_or_404(Product, pk=product_id)
        print(product, '🌹🌹🌹🌹🌹')
        basket.add(product, product_qty)
        bastketqty = basket.__len__()
        response = JsonResponse({'qty': bastketqty})
        return response


def basket_delete(request):
    basket = Basket(request)
    if request.method == 'POST':
        product_id = request.POST.get('productid')
        basket.delete(product_id)

        sub_total = basket.get_total_price()
        qty = basket.__len__()
        response = JsonResponse({'sub_total': sub_total, 'qty': qty})
        return response


def basket_update(request):
    basket = Basket(request)
    if request.method == 'POST':
        product_id = request.POST.get('productid')
        product_qty = request.POST.get('productqty')
        basket.update(product_id, product_qty)

        sub_total = basket.get_total_price()
        qty = basket.__len__()
        response = JsonResponse({'sub_total': sub_total, 'qty': qty})
        return response

store/views.py
from django.shortcuts import get_object_or_404, render

from .models import Category, Product


def home(request):
    products = Product.products.all()
    return render(request, 'store/home.html', {'products': products})


def product_details(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request, 'store/products/details.html', {'product': product})


def category_list(request, slug):
    category = get_object_or_404(Category, slug=slug)
    products = Product.objects.filter(category=category)
    return render(request, 'store/products/category.html', {'category': category, 'products': products})

templates/store/basket/summary.html
{% extends "../base.html" %}
{% load static %}
{% block title %}Basket Summary{% endblock %}
{% block content %}

<main class="pt-5">
  <div class="container">
    <h1 class="h5">Shopping basket</h1>
    {% for item in basket %}
    {% with product=item.product %}
    <div data-index="{{product.id}}" class="row mb-4 border product-item">
      <div class="col-md-3 col-lg-2 order-md-first bg-light">
        <img class="img-fluid mx-auto d-block" width="120px" alt="Responsive image" src="{{ product.image.url }}">
      </div>
      <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
        <a href="{{ product.get_absolute_url }}" class="text-decoration-none text-reset">
          <h1 class="h5 pt-2">{{ product.title }}</h1>
        </a>
        <div class="border">
          <div class="col border-bottom">
            <div class="row p-3">
              <div class="col-6">Hardback Book</div>
              <div class="col-6 text-end"><span class="h6 fw-bold">£{{ product.price }}</span></div>
            </div>
          </div>
          <div class="col">
            <div class="row p-3">
              <div class="col-12">
                <label for="select">Qty</label>
                <select id="select{{product.id}}">
                  <option selected>
                    {{item.qty}}
                  </option>
                  <option value="">1</option>
                  <option value="">2</option>
                  <option value="">3</option>
                  <option value="">4</option>
                </select>
                <button type="button" id="update-button" data-index="{{product.id}}"
                  class="btn btn-outline-secondary btn-sm update-button">
                  Update
                </button>
                <button type="button" id="delete-button" data-index="{{product.id}}"
                  class="btn btn-outline-secondary btn-sm delete-button">
                  Delete
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endwith %}
    {% endfor %}
    <div class="col-12 text-end">
      <div class="h6 fw-bold">Sub Total: £<div id="subtotal" class="d-inline-flex">{{basket.get_total_price}}</div></div>
    </div>
  </div>
</main>

<script>
  // delete from basket
   $(document).on('click', '.delete-button', function(e){
        e.preventDefault()
        var prodid = $(this).data('index');
        $.ajax({
            type:'POST',
            url: '{% url "basket:basket_delete" %}',
            data:{
                productid:prodid,
                csrfmiddlewaretoken:'{{csrf_token}}',
            },
            success: function(res){
                console.log(res)
                $('.product-item[data-index="' + prodid + '"]').remove()
                document.getElementById("basket-qty").innerHTML = res.qty
                document.getElementById("subtotal").innerHTML = res.sub_total
            },
            error: function(e){console.log(e)}
        })
    })
  // update the basket
   $(document).on('click', '.update-button', function(e){
        e.preventDefault()
        var prodid = $(this).data('index');
        $.ajax({
            type:'POST',
            url: '{% url "basket:basket_update" %}',
            data:{
                productid:prodid,
                productqty:$('#select'+prodid+' option:selected').text(),
                csrfmiddlewaretoken:'{{csrf_token}}',
            },
            success: function(res){
                console.log(res)
                document.getElementById("basket-qty").innerHTML = res.qty
                document.getElementById("subtotal").innerHTML = res.sub_total
            },
            error: function(e){console.log(e)}
        })
    })
</script>

{% endblock %}